CREATE TABLE IF NOT EXISTS `users` (
	`id` VARCHAR(36) NOT NULL,
	`first_name` VARCHAR(36) NOT NULL,
	`last_name` VARCHAR(36) NOT NULL,
	`gender` VARCHAR(36) NOT NULL,
	`date_of_birth` TIMESTAMP NOT NULL,
	`status` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` VARCHAR(36) NOT NULL,
	`updated_by` VARCHAR(36) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `identities` (
	`id` VARCHAR(36) NOT NULL,
	`type` VARCHAR(36) NOT NULL,
	`value` VARCHAR(36) NOT NULL,
	`user_id` VARCHAR(36),
	`status` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` VARCHAR(36) NOT NULL,
	`updated_by` VARCHAR(36) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `meta_attributes` (
	`id` VARCHAR(36) NOT NULL,
	`name` VARCHAR(36) NOT NULL,
	`description` VARCHAR(36) NOT NULL,
	`schema` VARCHAR(36),
	`status` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` VARCHAR(36) NOT NULL,
	`updated_by` VARCHAR(36) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `attributes` (
	`id` VARCHAR(36) NOT NULL,
	`user_id` VARCHAR(36) NOT NULL,
	`meta_attribute_id` VARCHAR(36) NOT NULL,
	`value` VARCHAR(36),
	`status` VARCHAR(36) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created_by` VARCHAR(36) NOT NULL,
	`updated_by` VARCHAR(36) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;